"""Additional recipes: age 6-12mo weaning purées + age 3-6yr big-kid foods.
Appended to the existing 50 recipes to reach 75+."""

EXTRA_RECIPES = [
    # 6-12 months — First Foods / Weaning (12 recipes)
    {"title": {"en": "Apple Purée", "hi": "सेब प्यूरी", "te": "యాపిల్ ప్యూరీ"},
     "category": "snack", "region": "pan-india", "age_min": 6, "age_max": 18,
     "prep_time": 2, "cook_time": 10, "difficulty": "easy",
     "description": "First food for babies — naturally sweet, gentle.",
     "ingredients": ["1 apple peeled, cored", "2 tbsp water"],
     "steps": ["Chop apple into chunks", "Steam 10 minutes until soft", "Blend smooth with water", "Cool before serving"],
     "nutrition": {"calories": 90, "protein": 0, "carbs": 22, "fat": 0, "fiber": "high"},
     "image": "https://images.pexels.com/photos/1630309/pexels-photo-1630309.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.9},
    {"title": {"en": "Mashed Dal Water", "hi": "दाल का पानी", "te": "పప్పు నీళ్లు"},
     "category": "lunch", "region": "pan-india", "age_min": 6, "age_max": 12,
     "prep_time": 5, "cook_time": 20, "difficulty": "easy",
     "description": "Protein-rich broth — baby's first tasting.",
     "ingredients": ["2 tbsp moong dal", "1 cup water", "Pinch turmeric"],
     "steps": ["Pressure cook dal with turmeric", "Strain clear dal water", "Serve warm in spoon"],
     "nutrition": {"calories": 40, "protein": 3, "carbs": 6, "fat": 0, "iron": "medium"},
     "image": "https://images.pexels.com/photos/5560743/pexels-photo-5560743.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Rice Kanji", "hi": "चावल का मांड", "te": "బియ్యం గంజి"},
     "category": "breakfast", "region": "south", "age_min": 6, "age_max": 18,
     "prep_time": 5, "cook_time": 25, "difficulty": "easy",
     "description": "Strained rice water — soft, soothing for tiny tummies.",
     "ingredients": ["2 tbsp rice", "2 cups water", "Pinch rock salt"],
     "steps": ["Cook rice in extra water", "Strain liquid into a cup", "Cool to lukewarm", "Serve by spoon"],
     "nutrition": {"calories": 50, "protein": 1, "carbs": 11, "fat": 0},
     "image": "https://images.pexels.com/photos/6646057/pexels-photo-6646057.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "Carrot Purée", "hi": "गाजर प्यूरी", "te": "క్యారెట్ ప్యూరీ"},
     "category": "snack", "region": "pan-india", "age_min": 6, "age_max": 18,
     "prep_time": 3, "cook_time": 10, "difficulty": "easy",
     "description": "Vitamin A powerhouse for bright eyes.",
     "ingredients": ["1 carrot peeled", "2 tbsp water"],
     "steps": ["Steam carrot until soft", "Blend smooth", "Cool and serve"],
     "nutrition": {"calories": 30, "protein": 1, "carbs": 7, "fat": 0, "vitamin_a": "high"},
     "image": "https://images.pexels.com/photos/5945767/pexels-photo-5945767.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Ragi Ambali", "hi": "रागी अंबली", "te": "రాగి అంబలి"},
     "category": "breakfast", "region": "south", "age_min": 8, "age_max": 24,
     "prep_time": 5, "cook_time": 10, "difficulty": "easy",
     "description": "Fermented ragi porridge — calcium-rich traditional weaning food.",
     "ingredients": ["2 tbsp ragi flour", "1 cup water", "Pinch rock salt"],
     "steps": ["Mix ragi with little water", "Add to boiling water", "Stir 8 min until thick", "Cool, thin to drinkable consistency"],
     "nutrition": {"calories": 90, "protein": 2, "carbs": 20, "fat": 0, "calcium": "high"},
     "image": "https://images.pexels.com/photos/6363501/pexels-photo-6363501.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.9},
    {"title": {"en": "Pumpkin Mash", "hi": "कद्दू मसल", "te": "గుమ్మడికాయ"},
     "category": "lunch", "region": "pan-india", "age_min": 7, "age_max": 24,
     "prep_time": 3, "cook_time": 12, "difficulty": "easy",
     "description": "Sweet pumpkin mash — rich in beta-carotene.",
     "ingredients": ["1 cup chopped pumpkin", "1 tsp ghee"],
     "steps": ["Steam pumpkin soft", "Mash smooth", "Add ghee", "Serve warm"],
     "nutrition": {"calories": 60, "protein": 1, "carbs": 12, "fat": 2, "vitamin_a": "high"},
     "image": "https://images.pexels.com/photos/5945919/pexels-photo-5945919.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "Avocado Mash", "hi": "एवोकाडो", "te": "అవకాడో"},
     "category": "snack", "region": "pan-india", "age_min": 6, "age_max": 24,
     "prep_time": 2, "cook_time": 0, "difficulty": "easy",
     "description": "Healthy fats for brain development.",
     "ingredients": ["1/2 ripe avocado", "Squeeze lemon"],
     "steps": ["Scoop avocado", "Mash smooth", "Add tiny squeeze lemon", "Serve immediately"],
     "nutrition": {"calories": 120, "protein": 2, "carbs": 6, "fat": 11, "omega3": "good"},
     "image": "https://images.pexels.com/photos/2228553/pexels-photo-2228553.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.8},
    {"title": {"en": "Banana Rice Mash", "hi": "केला चावल", "te": "అరటి అన్నం"},
     "category": "lunch", "region": "pan-india", "age_min": 8, "age_max": 24,
     "prep_time": 3, "cook_time": 0, "difficulty": "easy",
     "description": "Comforting mash of soft rice and banana.",
     "ingredients": ["1/4 cup cooked rice", "1/2 ripe banana", "1 tsp ghee"],
     "steps": ["Mash rice and banana together", "Add ghee", "Serve warm"],
     "nutrition": {"calories": 140, "protein": 2, "carbs": 30, "fat": 2},
     "image": "https://images.pexels.com/photos/2116020/pexels-photo-2116020.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Spinach Dal Soup", "hi": "पालक सूप", "te": "పాలక్ సూప్"},
     "category": "dinner", "region": "pan-india", "age_min": 8, "age_max": 24,
     "prep_time": 5, "cook_time": 15, "difficulty": "easy",
     "description": "Iron-rich smooth soup for iron-deficient babies.",
     "ingredients": ["2 tbsp moong dal", "1/4 cup spinach", "Pinch cumin", "1 tsp ghee"],
     "steps": ["Pressure cook dal", "Blanch spinach", "Blend together smooth", "Temper with ghee+cumin"],
     "nutrition": {"calories": 90, "protein": 5, "carbs": 12, "fat": 3, "iron": "high"},
     "image": "https://images.pexels.com/photos/5946970/pexels-photo-5946970.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "Sweet Potato Purée", "hi": "शकरकंद प्यूरी", "te": "చిలకడ ప్యూరీ"},
     "category": "snack", "region": "pan-india", "age_min": 6, "age_max": 18,
     "prep_time": 3, "cook_time": 15, "difficulty": "easy",
     "description": "Naturally sweet, loaded with vitamins.",
     "ingredients": ["1 small sweet potato", "1 tsp ghee"],
     "steps": ["Boil until fork-tender", "Peel and blend smooth", "Mix in ghee", "Cool to warm"],
     "nutrition": {"calories": 120, "protein": 2, "carbs": 26, "fat": 2, "vitamin_a": "high"},
     "image": "https://images.pexels.com/photos/5945896/pexels-photo-5945896.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Pear Purée", "hi": "नाशपाती", "te": "బేరి"},
     "category": "snack", "region": "pan-india", "age_min": 6, "age_max": 18,
     "prep_time": 3, "cook_time": 8, "difficulty": "easy",
     "description": "Hypoallergenic first fruit — gentle on tummies.",
     "ingredients": ["1 ripe pear peeled"],
     "steps": ["Chop and steam 6 min", "Blend smooth", "Serve"],
     "nutrition": {"calories": 80, "protein": 0, "carbs": 20, "fat": 0, "fiber": "high"},
     "image": "https://images.pexels.com/photos/568471/pexels-photo-568471.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Chicken Stew (mild)", "hi": "चिकन स्टू", "te": "చికెన్ స్టూ"},
     "category": "dinner", "region": "south", "age_min": 10, "age_max": 36,
     "prep_time": 10, "cook_time": 25, "difficulty": "medium",
     "description": "Gentle coconut-milk stew — iron and protein.",
     "ingredients": ["30g minced chicken", "1/2 cup coconut milk", "Mixed veggies", "Curry leaves"],
     "steps": ["Cook chicken tender", "Add veggies and coconut milk", "Simmer till thick", "Cool and serve"],
     "nutrition": {"calories": 180, "protein": 10, "carbs": 8, "fat": 12, "protein_level": "high"},
     "image": "https://images.pexels.com/photos/5560802/pexels-photo-5560802.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.6},

    # 3-6 years — Big kid foods (13 recipes)
    {"title": {"en": "Veggie Uttapam", "hi": "सब्जी उत्तपम", "te": "కూరగాయల ఉత్తప్పం"},
     "category": "breakfast", "region": "south", "age_min": 36, "age_max": 84,
     "prep_time": 5, "cook_time": 10, "difficulty": "easy",
     "description": "Mini pancakes topped with colorful veggies.",
     "ingredients": ["1 cup dosa batter", "Diced onion, tomato, capsicum", "1 tsp ghee"],
     "steps": ["Spread batter on tawa (small rounds)", "Sprinkle veggies on top", "Cook till crisp", "Serve with chutney"],
     "nutrition": {"calories": 220, "protein": 7, "carbs": 36, "fat": 5},
     "image": "https://images.pexels.com/photos/9609839/pexels-photo-9609839.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "School Tiffin Paratha Roll", "hi": "पराठा रोल", "te": "పరాఠా రోల్"},
     "category": "lunch", "region": "pan-india", "age_min": 36, "age_max": 84,
     "prep_time": 15, "cook_time": 10, "difficulty": "medium",
     "description": "Perfect tiffin — paneer, veggies rolled in wheat.",
     "ingredients": ["Wheat paratha", "2 tbsp crumbled paneer", "Grated carrot", "Pinch chaat masala"],
     "steps": ["Crumble paneer with masala", "Spread on paratha", "Add grated carrot", "Roll tight, cut in half"],
     "nutrition": {"calories": 280, "protein": 12, "carbs": 36, "fat": 10},
     "image": "https://images.pexels.com/photos/7218637/pexels-photo-7218637.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.9},
    {"title": {"en": "Curd Sandwich", "hi": "दही सैंडविच", "te": "పెరుగు శాండ్విచ్"},
     "category": "snack", "region": "pan-india", "age_min": 36, "age_max": 84,
     "prep_time": 5, "cook_time": 3, "difficulty": "easy",
     "description": "Cooling hung-curd sandwich with cucumber.",
     "ingredients": ["Whole wheat bread", "2 tbsp hung curd", "Cucumber slices", "Mint leaves"],
     "steps": ["Mix curd with chopped mint", "Spread on bread", "Add cucumber", "Grill or serve fresh"],
     "nutrition": {"calories": 200, "protein": 8, "carbs": 28, "fat": 6},
     "image": "https://images.pexels.com/photos/5946628/pexels-photo-5946628.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.6},
    {"title": {"en": "Fruit Yogurt Parfait", "hi": "फ्रूट पारफे", "te": "ఫ్రూట్ పార్ఫే"},
     "category": "snack", "region": "pan-india", "age_min": 30, "age_max": 84,
     "prep_time": 5, "cook_time": 0, "difficulty": "easy",
     "description": "Layered yogurt, fruits and nuts — Instagram-worthy!",
     "ingredients": ["1/2 cup yogurt", "Chopped banana, berries", "1 tsp honey", "Crushed almond"],
     "steps": ["Layer yogurt, fruit, yogurt in cup", "Top with nuts", "Drizzle honey"],
     "nutrition": {"calories": 180, "protein": 7, "carbs": 28, "fat": 5, "probiotic": "yes"},
     "image": "https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.9},
    {"title": {"en": "Mini Vegetable Cutlets", "hi": "सब्ज़ी कटलेट", "te": "కూరగాయల కట్లెట్"},
     "category": "snack", "region": "pan-india", "age_min": 36, "age_max": 84,
     "prep_time": 15, "cook_time": 10, "difficulty": "medium",
     "description": "Crispy on outside, soft inside — hidden veggie power.",
     "ingredients": ["Boiled potato", "Grated carrot, peas", "Breadcrumbs", "1 tsp ghee"],
     "steps": ["Mix mashed potato with veggies", "Shape into small cutlets", "Coat in crumbs", "Pan-fry both sides"],
     "nutrition": {"calories": 160, "protein": 4, "carbs": 24, "fat": 5},
     "image": "https://images.pexels.com/photos/5560749/pexels-photo-5560749.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "Palak Rice Balls", "hi": "पालक राइस बॉल्स", "te": "పాలక్ రైస్ బాల్స్"},
     "category": "lunch", "region": "pan-india", "age_min": 36, "age_max": 84,
     "prep_time": 10, "cook_time": 10, "difficulty": "medium",
     "description": "Fun-to-eat green rice balls — iron boost.",
     "ingredients": ["1 cup cooked rice", "1/4 cup palak purée", "1 tsp ghee", "Pinch salt"],
     "steps": ["Mix rice with palak and ghee", "Roll into bite balls", "Serve with raita"],
     "nutrition": {"calories": 230, "protein": 5, "carbs": 40, "fat": 5, "iron": "high"},
     "image": "https://images.pexels.com/photos/5560767/pexels-photo-5560767.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Stuffed Masala Idli", "hi": "मसाला इडली", "te": "మసాలా ఇడ్లీ"},
     "category": "breakfast", "region": "south", "age_min": 30, "age_max": 84,
     "prep_time": 10, "cook_time": 15, "difficulty": "medium",
     "description": "Idli with mild masala coating — zesty morning.",
     "ingredients": ["Mini idlis", "Pinch red chili powder", "1 tsp ghee", "Curry leaves", "Mustard seeds"],
     "steps": ["Temper spices in ghee", "Toss warm idlis in tempering", "Serve immediately"],
     "nutrition": {"calories": 200, "protein": 6, "carbs": 34, "fat": 5},
     "image": "https://images.pexels.com/photos/14737073/pexels-photo-14737073.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.6},
    {"title": {"en": "Chana Chaat", "hi": "चना चाट", "te": "శనగ చాట్"},
     "category": "snack", "region": "north", "age_min": 48, "age_max": 84,
     "prep_time": 10, "cook_time": 0, "difficulty": "easy",
     "description": "Protein-packed chickpea salad — great after-school snack.",
     "ingredients": ["1/2 cup boiled chana", "Chopped tomato, cucumber", "1 tsp lemon juice", "Mint leaves"],
     "steps": ["Toss all together", "Chill 5 minutes", "Serve fresh"],
     "nutrition": {"calories": 180, "protein": 10, "carbs": 28, "fat": 3, "protein_level": "high"},
     "image": "https://images.pexels.com/photos/5560744/pexels-photo-5560744.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.7},
    {"title": {"en": "Grilled Cheese Chapati", "hi": "चपाती पिज़्ज़ा", "te": "చపాతీ పిజ్జా"},
     "category": "dinner", "region": "pan-india", "age_min": 36, "age_max": 84,
     "prep_time": 5, "cook_time": 5, "difficulty": "easy",
     "description": "Chapati pizza that kids love — veggies hidden!",
     "ingredients": ["1 chapati", "1 tbsp tomato paste", "2 tbsp grated cheese", "Chopped veggies"],
     "steps": ["Spread paste on chapati", "Top with veggies and cheese", "Grill 3 min until melted", "Slice and serve"],
     "nutrition": {"calories": 260, "protein": 10, "carbs": 32, "fat": 10, "calcium": "good"},
     "image": "https://images.pexels.com/photos/5560741/pexels-photo-5560741.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.9},
    {"title": {"en": "Mango Smoothie Bowl", "hi": "आम स्मूदी", "te": "మామిడి స్మూదీ"},
     "category": "breakfast", "region": "pan-india", "age_min": 30, "age_max": 84,
     "prep_time": 5, "cook_time": 0, "difficulty": "easy",
     "description": "Summer sunshine in a bowl.",
     "ingredients": ["1 ripe mango", "1/2 cup yogurt", "1 tbsp oats", "Chopped nuts"],
     "steps": ["Blend mango + yogurt + oats", "Pour in bowl", "Top with nuts"],
     "nutrition": {"calories": 220, "protein": 6, "carbs": 42, "fat": 4, "vitamin_c": "high"},
     "image": "https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.9},
    {"title": {"en": "Kid-Friendly Biryani", "hi": "बच्चों की बिरयानी", "te": "పిల్లల బిర్యానీ"},
     "category": "lunch", "region": "pan-india", "age_min": 36, "age_max": 84,
     "prep_time": 15, "cook_time": 25, "difficulty": "medium",
     "description": "Mild, fragrant one-pot rice — no chili.",
     "ingredients": ["1/2 cup basmati", "Mixed veggies", "1 tsp ghee", "Mild whole spices", "Mint"],
     "steps": ["Sauté spices in ghee", "Add veggies", "Add rinsed rice and water", "Cover cook 15 min", "Garnish mint"],
     "nutrition": {"calories": 280, "protein": 7, "carbs": 48, "fat": 6},
     "image": "https://images.pexels.com/photos/9609844/pexels-photo-9609844.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Peanut Butter Toast", "hi": "पीनट बटर टोस्ट", "te": "పీనట్ బటర్ టోస్ట్"},
     "category": "breakfast", "region": "pan-india", "age_min": 36, "age_max": 84,
     "prep_time": 2, "cook_time": 2, "difficulty": "easy",
     "description": "Quick protein-packed morning.",
     "ingredients": ["Whole wheat bread", "1 tbsp natural peanut butter", "Sliced banana"],
     "steps": ["Toast bread", "Spread peanut butter", "Top with banana slices"],
     "nutrition": {"calories": 260, "protein": 9, "carbs": 34, "fat": 10},
     "image": "https://images.pexels.com/photos/1087917/pexels-photo-1087917.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.7},
    {"title": {"en": "Homemade Nachni Cookies", "hi": "रागी कुकीज़", "te": "రాగి కుకీస్"},
     "category": "snack", "region": "south", "age_min": 36, "age_max": 84,
     "prep_time": 15, "cook_time": 15, "difficulty": "medium",
     "description": "Guilt-free after-school treat.",
     "ingredients": ["1/2 cup ragi flour", "2 tbsp jaggery powder", "2 tbsp ghee", "1 tbsp milk"],
     "steps": ["Mix to soft dough", "Shape small rounds", "Bake 180C for 15 min", "Cool before storing"],
     "nutrition": {"calories": 140, "protein": 3, "carbs": 20, "fat": 5, "calcium": "high"},
     "image": "https://images.pexels.com/photos/6219885/pexels-photo-6219885.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
]
