"""Seed data: 50 traditional Indian recipes suitable for 2-3 year olds."""

RECIPES = [
    # Breakfast (12)
    {"title": {"en": "Ragi Porridge", "hi": "रागी दलिया", "te": "రాగి గంజి"},
     "category": "breakfast", "region": "south", "age_min": 18, "age_max": 60,
     "prep_time": 5, "cook_time": 15, "difficulty": "easy",
     "description": "Iron-rich finger millet porridge, perfect for growing toddlers.",
     "ingredients": ["2 tbsp ragi flour", "1 cup milk", "1 tsp jaggery", "Pinch of cardamom"],
     "steps": ["Mix ragi flour with little water to form smooth paste", "Boil milk in a pan", "Add ragi paste, stir continuously", "Cook 10 minutes until thick", "Add jaggery and cardamom, serve warm"],
     "nutrition": {"calories": 180, "protein": 6, "carbs": 28, "fat": 4, "iron": "high", "calcium": "high"},
     "image": "https://images.pexels.com/photos/6363501/pexels-photo-6363501.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Vegetable Upma", "hi": "सब्ज़ी उपमा", "te": "కూరగాయల ఉప్మా"},
     "category": "breakfast", "region": "south", "age_min": 24, "age_max": 72,
     "prep_time": 10, "cook_time": 15, "difficulty": "easy",
     "description": "Soft semolina with colorful vegetables — a complete meal.",
     "ingredients": ["1/2 cup semolina", "1 small carrot diced", "1 tbsp peas", "1 tsp ghee", "Pinch of turmeric"],
     "steps": ["Dry roast semolina until aromatic", "Heat ghee, add vegetables, sauté 5 min", "Add 1.5 cups water, bring to boil", "Slowly stir in semolina", "Cook 5 min covered, fluff and serve"],
     "nutrition": {"calories": 210, "protein": 7, "carbs": 34, "fat": 5},
     "image": "https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "Mini Idli with Ghee", "hi": "मिनी इडली", "te": "మినీ ఇడ్లీ"},
     "category": "breakfast", "region": "south", "age_min": 18, "age_max": 72,
     "prep_time": 10, "cook_time": 15, "difficulty": "medium",
     "description": "Soft steamed rice cakes — gentle on little tummies.",
     "ingredients": ["1 cup idli batter", "1 tsp ghee", "Pinch of salt"],
     "steps": ["Grease mini idli molds with ghee", "Pour batter into molds", "Steam 10 minutes", "Cool slightly, drizzle ghee, serve"],
     "nutrition": {"calories": 150, "protein": 5, "carbs": 28, "fat": 3},
     "image": "https://images.pexels.com/photos/14737073/pexels-photo-14737073.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.9},
    {"title": {"en": "Poha with Veggies", "hi": "पोहा", "te": "అటుకులు"},
     "category": "breakfast", "region": "west", "age_min": 24, "age_max": 72,
     "prep_time": 10, "cook_time": 10, "difficulty": "easy",
     "description": "Flattened rice with vegetables, light and easy to digest.",
     "ingredients": ["1 cup poha", "1 small potato diced", "2 tbsp peas", "1 tsp ghee", "Pinch turmeric", "1 tsp lemon juice"],
     "steps": ["Rinse poha, drain, keep aside", "Heat ghee, add turmeric, vegetables", "Cook veggies 6 min", "Add poha, gently mix", "Squeeze lemon, serve"],
     "nutrition": {"calories": 190, "protein": 4, "carbs": 36, "fat": 4},
     "image": "https://images.pexels.com/photos/9609848/pexels-photo-9609848.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.6},
    {"title": {"en": "Besan Chilla", "hi": "बेसन चीला", "te": "శనగపిండి చిల్లా"},
     "category": "breakfast", "region": "north", "age_min": 24, "age_max": 72,
     "prep_time": 5, "cook_time": 10, "difficulty": "easy",
     "description": "Gram flour pancake — protein-rich breakfast.",
     "ingredients": ["1/2 cup besan", "1 tbsp grated carrot", "Pinch ajwain", "Water to make batter", "1 tsp ghee"],
     "steps": ["Mix besan with water to pancake batter", "Add carrot, ajwain, salt", "Pour on hot tawa, spread", "Cook both sides with ghee", "Cut into strips and serve"],
     "nutrition": {"calories": 200, "protein": 10, "carbs": 22, "fat": 7, "protein_level": "high"},
     "image": "https://images.pexels.com/photos/4331491/pexels-photo-4331491.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "Suji Halwa", "hi": "सूजी हलवा", "te": "రవ్వ హల్వా"},
     "category": "breakfast", "region": "north", "age_min": 18, "age_max": 72,
     "prep_time": 2, "cook_time": 10, "difficulty": "easy",
     "description": "Warm semolina pudding with ghee and nuts.",
     "ingredients": ["1/4 cup semolina", "1 tsp ghee", "1 tbsp jaggery", "1 cup milk", "Pinch cardamom"],
     "steps": ["Roast semolina in ghee until golden", "Add warm milk slowly, stir", "Cook until thick", "Mix in jaggery and cardamom", "Serve warm"],
     "nutrition": {"calories": 220, "protein": 6, "carbs": 38, "fat": 6},
     "image": "https://images.pexels.com/photos/12819082/pexels-photo-12819082.jpeg",
     "ayurvedic": True, "scientific": False, "rating": 4.5},
    {"title": {"en": "Banana Oats", "hi": "केला ओट्स", "te": "అరటి ఓట్స్"},
     "category": "breakfast", "region": "pan-india", "age_min": 18, "age_max": 72,
     "prep_time": 2, "cook_time": 8, "difficulty": "easy",
     "description": "Creamy oats with banana — fiber-rich start.",
     "ingredients": ["1/4 cup oats", "1 small banana mashed", "1 cup milk", "1 tsp honey (above 1yr)"],
     "steps": ["Boil milk, add oats", "Cook 5 min stirring", "Add banana, mix well", "Drizzle honey, serve"],
     "nutrition": {"calories": 200, "protein": 7, "carbs": 36, "fat": 4, "fiber": "high"},
     "image": "https://images.pexels.com/photos/1351238/pexels-photo-1351238.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.6},
    {"title": {"en": "Paneer Paratha Roll", "hi": "पनीर पराठा", "te": "పనీర్ పరాఠా"},
     "category": "breakfast", "region": "north", "age_min": 24, "age_max": 72,
     "prep_time": 15, "cook_time": 10, "difficulty": "medium",
     "description": "Soft wheat paratha stuffed with crumbled paneer.",
     "ingredients": ["1/2 cup wheat flour", "2 tbsp paneer crumbled", "Pinch salt", "1 tsp ghee"],
     "steps": ["Knead soft dough", "Stuff paneer in dough ball", "Roll gently", "Cook on tawa with ghee both sides", "Roll up and serve"],
     "nutrition": {"calories": 250, "protein": 10, "carbs": 30, "fat": 9, "calcium": "high"},
     "image": "https://images.pexels.com/photos/7218637/pexels-photo-7218637.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Methi Thepla", "hi": "मेथी थेपला", "te": "మెంతి థేప్లా"},
     "category": "breakfast", "region": "west", "age_min": 30, "age_max": 72,
     "prep_time": 15, "cook_time": 10, "difficulty": "medium",
     "description": "Fenugreek flatbread — iron and calcium boost.",
     "ingredients": ["1/2 cup wheat flour", "2 tbsp chopped methi", "1 tbsp yogurt", "Pinch turmeric"],
     "steps": ["Mix all ingredients into dough", "Roll thin rounds", "Cook on tawa with ghee", "Serve with yogurt"],
     "nutrition": {"calories": 180, "protein": 6, "carbs": 28, "fat": 5, "iron": "high"},
     "image": "https://images.pexels.com/photos/5560744/pexels-photo-5560744.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.5},
    {"title": {"en": "Rice Kheer", "hi": "चावल खीर", "te": "పాల పాయసం"},
     "category": "breakfast", "region": "pan-india", "age_min": 18, "age_max": 72,
     "prep_time": 5, "cook_time": 25, "difficulty": "easy",
     "description": "Creamy rice pudding for happy mornings.",
     "ingredients": ["2 tbsp rice", "1 cup milk", "1 tbsp jaggery", "Pinch cardamom", "Few raisins"],
     "steps": ["Cook rice in milk on low heat", "Stir often 20 min until creamy", "Add jaggery and cardamom", "Top with raisins, serve warm"],
     "nutrition": {"calories": 210, "protein": 6, "carbs": 34, "fat": 5},
     "image": "https://images.pexels.com/photos/14737076/pexels-photo-14737076.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.9},
    {"title": {"en": "Sweet Potato Mash", "hi": "शकरकंद", "te": "చిలకడ దుంప"},
     "category": "breakfast", "region": "pan-india", "age_min": 12, "age_max": 48,
     "prep_time": 5, "cook_time": 15, "difficulty": "easy",
     "description": "Soft sweet potato mash — beta carotene rich.",
     "ingredients": ["1 small sweet potato", "1 tsp ghee", "Pinch cinnamon"],
     "steps": ["Boil sweet potato until soft", "Peel and mash", "Mix ghee and cinnamon", "Serve warm"],
     "nutrition": {"calories": 150, "protein": 3, "carbs": 28, "fat": 3, "vitamin_a": "high"},
     "image": "https://images.pexels.com/photos/5945896/pexels-photo-5945896.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "Moong Dal Cheela", "hi": "मूंग दाल चीला", "te": "పెసర పిండి చీలా"},
     "category": "breakfast", "region": "north", "age_min": 24, "age_max": 72,
     "prep_time": 240, "cook_time": 10, "difficulty": "medium",
     "description": "Green gram lentil crepes — high protein.",
     "ingredients": ["1/4 cup moong dal soaked", "Pinch ginger", "Pinch cumin", "1 tsp ghee"],
     "steps": ["Grind soaked dal to smooth paste", "Add spices", "Pour thin on tawa", "Cook both sides with ghee", "Serve warm"],
     "nutrition": {"calories": 180, "protein": 11, "carbs": 22, "fat": 4, "protein_level": "high"},
     "image": "https://images.pexels.com/photos/5560747/pexels-photo-5560747.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.6},

    # Lunch (14)
    {"title": {"en": "Dal Khichdi", "hi": "दाल खिचड़ी", "te": "పప్పు ఖిచడి"},
     "category": "lunch", "region": "pan-india", "age_min": 12, "age_max": 72,
     "prep_time": 10, "cook_time": 20, "difficulty": "easy",
     "description": "The ultimate comfort food — rice and lentils cooked to mushy goodness.",
     "ingredients": ["1/4 cup rice", "2 tbsp moong dal", "1 tsp ghee", "Pinch turmeric", "Pinch salt", "Small cube ginger"],
     "steps": ["Wash rice and dal together", "Pressure cook with 2 cups water, turmeric, ginger, salt — 3 whistles", "Mash lightly", "Top with ghee, serve warm"],
     "nutrition": {"calories": 220, "protein": 9, "carbs": 38, "fat": 4, "protein_level": "high"},
     "image": "https://images.pexels.com/photos/6646060/pexels-photo-6646060.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.9},
    {"title": {"en": "Vegetable Pulao", "hi": "सब्ज़ी पुलाव", "te": "కూరగాయల పులావ్"},
     "category": "lunch", "region": "pan-india", "age_min": 24, "age_max": 72,
     "prep_time": 10, "cook_time": 20, "difficulty": "medium",
     "description": "Fragrant rice with mixed vegetables.",
     "ingredients": ["1/2 cup basmati rice", "1/4 cup mixed veggies", "1 tsp ghee", "Whole spices (bay leaf, cardamom)"],
     "steps": ["Heat ghee, add spices", "Add veggies, sauté", "Add rinsed rice and water", "Cover and cook on low 15 min", "Fluff and serve"],
     "nutrition": {"calories": 240, "protein": 6, "carbs": 42, "fat": 5},
     "image": "https://images.pexels.com/photos/9609844/pexels-photo-9609844.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "Curd Rice", "hi": "दही चावल", "te": "పెరుగన్నం"},
     "category": "lunch", "region": "south", "age_min": 18, "age_max": 72,
     "prep_time": 2, "cook_time": 5, "difficulty": "easy",
     "description": "Cooling, probiotic rice — tummy's best friend.",
     "ingredients": ["1/2 cup cooked rice", "1/4 cup curd", "1 tsp ghee", "Pinch salt", "1/4 tsp mustard seeds"],
     "steps": ["Mash rice lightly", "Mix with curd and salt", "Temper ghee with mustard", "Pour over rice, serve"],
     "nutrition": {"calories": 180, "protein": 5, "carbs": 30, "fat": 4, "probiotic": "yes"},
     "image": "https://images.pexels.com/photos/14737072/pexels-photo-14737072.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Palak Dal", "hi": "पालक दाल", "te": "పాలకూర పప్పు"},
     "category": "lunch", "region": "pan-india", "age_min": 18, "age_max": 72,
     "prep_time": 5, "cook_time": 15, "difficulty": "easy",
     "description": "Spinach-lentil stew — iron powerhouse.",
     "ingredients": ["1/4 cup toor dal", "1/4 cup chopped palak", "1 tsp ghee", "Pinch cumin", "Pinch turmeric"],
     "steps": ["Pressure cook dal with turmeric 3 whistles", "Blanch and chop palak", "Temper ghee with cumin", "Add palak, cooked dal", "Simmer 5 min, serve with rice"],
     "nutrition": {"calories": 170, "protein": 10, "carbs": 22, "fat": 4, "iron": "high"},
     "image": "https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Sambar Rice", "hi": "सांभर चावल", "te": "సాంబార్ అన్నం"},
     "category": "lunch", "region": "south", "age_min": 24, "age_max": 72,
     "prep_time": 15, "cook_time": 25, "difficulty": "medium",
     "description": "Tamarind-lentil stew with rice — complete protein meal.",
     "ingredients": ["1/2 cup rice", "2 tbsp toor dal", "Mixed vegetables", "Tamarind paste", "Sambar powder (mild)"],
     "steps": ["Cook dal with turmeric", "Boil veggies with tamarind", "Add dal and sambar powder", "Serve over rice"],
     "nutrition": {"calories": 230, "protein": 9, "carbs": 40, "fat": 4},
     "image": "https://images.pexels.com/photos/5560762/pexels-photo-5560762.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.6},
    {"title": {"en": "Aloo Paratha", "hi": "आलू पराठा", "te": "ఆలూ పరాఠా"},
     "category": "lunch", "region": "north", "age_min": 30, "age_max": 72,
     "prep_time": 15, "cook_time": 10, "difficulty": "medium",
     "description": "Stuffed potato flatbread — hearty and satisfying.",
     "ingredients": ["1/2 cup wheat flour", "1 small potato boiled", "Pinch cumin", "1 tsp ghee"],
     "steps": ["Mash potato with spices", "Stuff into dough ball", "Roll gently", "Cook on tawa with ghee"],
     "nutrition": {"calories": 240, "protein": 6, "carbs": 38, "fat": 7},
     "image": "https://images.pexels.com/photos/14737075/pexels-photo-14737075.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Rajma Chawal", "hi": "राजमा चावल", "te": "రాజ్మా అన్నం"},
     "category": "lunch", "region": "north", "age_min": 36, "age_max": 72,
     "prep_time": 480, "cook_time": 30, "difficulty": "medium",
     "description": "Kidney bean curry with rice — protein-rich classic.",
     "ingredients": ["1/4 cup soaked rajma", "1/2 cup rice", "Mild tomato gravy", "1 tsp ghee"],
     "steps": ["Pressure cook rajma 5 whistles", "Prepare mild tomato base", "Simmer rajma in gravy", "Serve with rice"],
     "nutrition": {"calories": 260, "protein": 12, "carbs": 44, "fat": 4},
     "image": "https://images.pexels.com/photos/5560748/pexels-photo-5560748.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.7},
    {"title": {"en": "Lauki Chana Dal", "hi": "लौकी चना दाल", "te": "సొరకాయ పప్పు"},
     "category": "lunch", "region": "pan-india", "age_min": 18, "age_max": 72,
     "prep_time": 10, "cook_time": 20, "difficulty": "easy",
     "description": "Bottle gourd and split gram — cooling and nutritious.",
     "ingredients": ["1/4 cup chana dal", "1 cup diced lauki", "Pinch turmeric", "1 tsp ghee"],
     "steps": ["Pressure cook dal and lauki with turmeric", "Mash lightly", "Temper with ghee and cumin", "Serve with rice"],
     "nutrition": {"calories": 180, "protein": 9, "carbs": 26, "fat": 4},
     "image": "https://images.pexels.com/photos/6646061/pexels-photo-6646061.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.5},
    {"title": {"en": "Tomato Rice", "hi": "टमाटर चावल", "te": "టొమాటో అన్నం"},
     "category": "lunch", "region": "south", "age_min": 24, "age_max": 72,
     "prep_time": 5, "cook_time": 15, "difficulty": "easy",
     "description": "Tangy tomato-flavored rice.",
     "ingredients": ["1/2 cup cooked rice", "1 tomato pureed", "1 tsp ghee", "Pinch turmeric"],
     "steps": ["Heat ghee, add turmeric and tomato puree", "Cook until thick", "Mix in rice", "Serve warm"],
     "nutrition": {"calories": 200, "protein": 4, "carbs": 36, "fat": 4},
     "image": "https://images.pexels.com/photos/5560769/pexels-photo-5560769.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.6},
    {"title": {"en": "Methi Dal", "hi": "मेथी दाल", "te": "మెంతి పప్పు"},
     "category": "lunch", "region": "pan-india", "age_min": 30, "age_max": 72,
     "prep_time": 10, "cook_time": 20, "difficulty": "easy",
     "description": "Fenugreek leaves with lentils — iron-rich.",
     "ingredients": ["1/4 cup moong dal", "2 tbsp chopped methi", "1 tsp ghee", "Pinch turmeric"],
     "steps": ["Cook dal with turmeric", "Sauté methi in ghee", "Mix with dal", "Serve with rice"],
     "nutrition": {"calories": 170, "protein": 9, "carbs": 24, "fat": 4, "iron": "high"},
     "image": "https://images.pexels.com/photos/5560746/pexels-photo-5560746.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.5},
    {"title": {"en": "Mixed Veg Curry Rice", "hi": "मिक्स वेज", "te": "మిక్స్ వెజ్"},
     "category": "lunch", "region": "pan-india", "age_min": 24, "age_max": 72,
     "prep_time": 10, "cook_time": 20, "difficulty": "easy",
     "description": "Mixed vegetable curry with soft rice.",
     "ingredients": ["Mixed veggies (carrot, peas, beans)", "1/2 cup rice", "Mild tomato gravy"],
     "steps": ["Steam veggies", "Prepare mild gravy", "Add veggies, simmer", "Serve with rice"],
     "nutrition": {"calories": 220, "protein": 6, "carbs": 38, "fat": 5},
     "image": "https://images.pexels.com/photos/5560778/pexels-photo-5560778.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.6},
    {"title": {"en": "Curd Rice with Pomegranate", "hi": "अनार दही चावल", "te": "దానిమ్మ పెరుగన్నం"},
     "category": "lunch", "region": "south", "age_min": 24, "age_max": 72,
     "prep_time": 5, "cook_time": 5, "difficulty": "easy",
     "description": "Cooling curd rice with pomegranate jewels.",
     "ingredients": ["1/2 cup rice", "1/4 cup curd", "2 tbsp pomegranate seeds", "Pinch salt"],
     "steps": ["Mash rice with curd", "Top with pomegranate", "Serve cool"],
     "nutrition": {"calories": 190, "protein": 5, "carbs": 32, "fat": 4},
     "image": "https://images.pexels.com/photos/5560759/pexels-photo-5560759.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Palak Paneer Rice", "hi": "पालक पनीर", "te": "పాలక్ పనీర్"},
     "category": "lunch", "region": "north", "age_min": 30, "age_max": 72,
     "prep_time": 10, "cook_time": 15, "difficulty": "medium",
     "description": "Spinach-paneer curry with rice.",
     "ingredients": ["1/4 cup palak puree", "2 tbsp paneer cubes", "1/2 cup rice", "1 tsp ghee"],
     "steps": ["Sauté palak puree in ghee", "Add paneer, simmer 5 min", "Serve with rice"],
     "nutrition": {"calories": 260, "protein": 12, "carbs": 32, "fat": 9, "iron": "high", "calcium": "high"},
     "image": "https://images.pexels.com/photos/6544378/pexels-photo-6544378.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Bhindi Rice", "hi": "भिंडी चावल", "te": "బెండకాయ అన్నం"},
     "category": "lunch", "region": "pan-india", "age_min": 30, "age_max": 72,
     "prep_time": 10, "cook_time": 15, "difficulty": "easy",
     "description": "Okra with rice — classic combo.",
     "ingredients": ["1/2 cup chopped bhindi", "1/2 cup rice", "1 tsp ghee", "Pinch turmeric"],
     "steps": ["Sauté bhindi until tender", "Mix with rice and ghee", "Serve"],
     "nutrition": {"calories": 210, "protein": 5, "carbs": 38, "fat": 5},
     "image": "https://images.pexels.com/photos/5560750/pexels-photo-5560750.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.5},

    # Snack (12)
    {"title": {"en": "Dhokla", "hi": "ढोकला", "te": "ధోక్లా"},
     "category": "snack", "region": "west", "age_min": 24, "age_max": 72,
     "prep_time": 10, "cook_time": 15, "difficulty": "medium",
     "description": "Steamed gram flour cake — soft, spongy and light.",
     "ingredients": ["1/2 cup besan", "2 tbsp yogurt", "Pinch turmeric", "1/4 tsp eno"],
     "steps": ["Mix besan, yogurt, turmeric with water", "Add eno, pour in greased plate", "Steam 12 minutes", "Cool, cut into squares"],
     "nutrition": {"calories": 160, "protein": 7, "carbs": 20, "fat": 4},
     "image": "https://images.pexels.com/photos/5560753/pexels-photo-5560753.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.7},
    {"title": {"en": "Banana Pancake", "hi": "केले का पैनकेक", "te": "అరటి పాన్కేక్"},
     "category": "snack", "region": "pan-india", "age_min": 18, "age_max": 72,
     "prep_time": 5, "cook_time": 10, "difficulty": "easy",
     "description": "Fluffy banana pancakes — naturally sweet.",
     "ingredients": ["1 banana", "2 tbsp wheat flour", "2 tbsp milk", "1 tsp ghee"],
     "steps": ["Mash banana, mix with flour and milk", "Pour small rounds on tawa", "Cook both sides with ghee", "Serve warm"],
     "nutrition": {"calories": 180, "protein": 4, "carbs": 32, "fat": 5},
     "image": "https://images.pexels.com/photos/4397924/pexels-photo-4397924.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.8},
    {"title": {"en": "Sabudana Kheer", "hi": "साबूदाना खीर", "te": "సగ్గుబియ్యం పాయసం"},
     "category": "snack", "region": "west", "age_min": 18, "age_max": 72,
     "prep_time": 30, "cook_time": 15, "difficulty": "easy",
     "description": "Tapioca pearl pudding — energy booster.",
     "ingredients": ["2 tbsp soaked sabudana", "1 cup milk", "1 tbsp jaggery", "Pinch cardamom"],
     "steps": ["Cook soaked sabudana in milk", "Stir until pearls translucent", "Add jaggery and cardamom", "Serve warm"],
     "nutrition": {"calories": 170, "protein": 4, "carbs": 32, "fat": 3},
     "image": "https://images.pexels.com/photos/12822047/pexels-photo-12822047.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.6},
    {"title": {"en": "Makhana Kheer", "hi": "मखाना खीर", "te": "మఖానా పాయసం"},
     "category": "snack", "region": "north", "age_min": 24, "age_max": 72,
     "prep_time": 5, "cook_time": 15, "difficulty": "easy",
     "description": "Fox nut pudding — calcium-rich.",
     "ingredients": ["1/4 cup makhana", "1 cup milk", "1 tbsp jaggery", "1 tsp ghee"],
     "steps": ["Roast makhana in ghee", "Crush lightly, add milk", "Simmer 10 min", "Add jaggery, serve"],
     "nutrition": {"calories": 180, "protein": 5, "carbs": 28, "fat": 5, "calcium": "high"},
     "image": "https://images.pexels.com/photos/6544378/pexels-photo-6544378.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Fruit Chaat", "hi": "फ्रूट चाट", "te": "పండ్ల చాట్"},
     "category": "snack", "region": "pan-india", "age_min": 18, "age_max": 72,
     "prep_time": 10, "cook_time": 0, "difficulty": "easy",
     "description": "Fresh fruits with gentle spice — vitamin C boost.",
     "ingredients": ["Banana", "Apple", "Pomegranate", "Pinch chaat masala (age 3+)"],
     "steps": ["Dice fruits tiny", "Mix gently", "Serve fresh"],
     "nutrition": {"calories": 120, "protein": 2, "carbs": 28, "fat": 1, "vitamin_c": "high"},
     "image": "https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.9},
    {"title": {"en": "Nuts & Dates Laddoo", "hi": "खजूर लड्डू", "te": "ఖర్జూర లడ్డూ"},
     "category": "snack", "region": "pan-india", "age_min": 24, "age_max": 72,
     "prep_time": 15, "cook_time": 5, "difficulty": "easy",
     "description": "Naturally sweet energy balls — iron-rich.",
     "ingredients": ["5 dates pitted", "1 tbsp almond powder", "1 tsp ghee"],
     "steps": ["Roast almond powder in ghee", "Blend dates into paste", "Mix, roll into balls", "Refrigerate"],
     "nutrition": {"calories": 150, "protein": 3, "carbs": 22, "fat": 6, "iron": "high"},
     "image": "https://images.pexels.com/photos/5986717/pexels-photo-5986717.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.9},
    {"title": {"en": "Boiled Egg Mash", "hi": "अंडा", "te": "గుడ్డు"},
     "category": "snack", "region": "pan-india", "age_min": 12, "age_max": 72,
     "prep_time": 2, "cook_time": 10, "difficulty": "easy",
     "description": "Simple boiled egg mash — complete protein.",
     "ingredients": ["1 egg", "Pinch salt", "1 tsp ghee"],
     "steps": ["Hard boil egg 8 min", "Peel and mash", "Mix with ghee", "Serve"],
     "nutrition": {"calories": 90, "protein": 7, "carbs": 1, "fat": 6, "protein_level": "high"},
     "image": "https://images.pexels.com/photos/1391487/pexels-photo-1391487.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.5},
    {"title": {"en": "Apple Halwa", "hi": "सेब का हलवा", "te": "యాపిల్ హల్వా"},
     "category": "snack", "region": "pan-india", "age_min": 12, "age_max": 72,
     "prep_time": 5, "cook_time": 15, "difficulty": "easy",
     "description": "Warm apple pudding with ghee.",
     "ingredients": ["1 apple grated", "1 tsp ghee", "1 tbsp jaggery", "Pinch cardamom"],
     "steps": ["Sauté grated apple in ghee", "Add jaggery, cook 10 min", "Add cardamom, serve warm"],
     "nutrition": {"calories": 140, "protein": 1, "carbs": 28, "fat": 4},
     "image": "https://images.pexels.com/photos/1855214/pexels-photo-1855214.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "Ragi Cookies", "hi": "रागी बिस्कुट", "te": "రాగి బిస్కెట్"},
     "category": "snack", "region": "south", "age_min": 24, "age_max": 72,
     "prep_time": 15, "cook_time": 20, "difficulty": "medium",
     "description": "Healthy ragi cookies — calcium-packed.",
     "ingredients": ["1/2 cup ragi flour", "2 tbsp jaggery", "2 tbsp ghee", "1 tbsp milk"],
     "steps": ["Mix all ingredients to dough", "Shape into small cookies", "Bake at 180C for 15 min"],
     "nutrition": {"calories": 130, "protein": 3, "carbs": 18, "fat": 5, "calcium": "high"},
     "image": "https://images.pexels.com/photos/6219885/pexels-photo-6219885.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "Sweet Lassi", "hi": "मीठी लस्सी", "te": "తీపి లస్సీ"},
     "category": "snack", "region": "north", "age_min": 18, "age_max": 72,
     "prep_time": 5, "cook_time": 0, "difficulty": "easy",
     "description": "Cooling yogurt drink.",
     "ingredients": ["1/2 cup curd", "1/4 cup water", "1 tbsp jaggery", "Pinch cardamom"],
     "steps": ["Blend all ingredients", "Serve chilled"],
     "nutrition": {"calories": 110, "protein": 4, "carbs": 16, "fat": 3, "probiotic": "yes"},
     "image": "https://images.pexels.com/photos/5946081/pexels-photo-5946081.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Carrot Halwa", "hi": "गाजर का हलवा", "te": "క్యారెట్ హల్వా"},
     "category": "snack", "region": "north", "age_min": 18, "age_max": 72,
     "prep_time": 10, "cook_time": 30, "difficulty": "medium",
     "description": "Classic carrot pudding — vitamin A rich.",
     "ingredients": ["1 cup grated carrot", "1/2 cup milk", "1 tbsp jaggery", "1 tsp ghee", "Pinch cardamom"],
     "steps": ["Cook carrot in milk until soft", "Add ghee and jaggery", "Cook until thick", "Serve warm"],
     "nutrition": {"calories": 180, "protein": 4, "carbs": 28, "fat": 6, "vitamin_a": "high"},
     "image": "https://images.pexels.com/photos/14737074/pexels-photo-14737074.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.9},
    {"title": {"en": "Coconut Ladoo", "hi": "नारियल लड्डू", "te": "కొబ్బరి లడ్డూ"},
     "category": "snack", "region": "south", "age_min": 24, "age_max": 72,
     "prep_time": 10, "cook_time": 10, "difficulty": "easy",
     "description": "Soft coconut balls — aromatic and healthy.",
     "ingredients": ["1 cup grated coconut", "1/4 cup condensed milk", "Pinch cardamom"],
     "steps": ["Cook coconut and milk together", "Stir until thick", "Cool slightly, roll into balls"],
     "nutrition": {"calories": 160, "protein": 2, "carbs": 18, "fat": 9},
     "image": "https://images.pexels.com/photos/5986663/pexels-photo-5986663.jpeg",
     "ayurvedic": True, "scientific": False, "rating": 4.7},

    # Dinner (12)
    {"title": {"en": "Soft Chapati with Dal", "hi": "चपाती दाल", "te": "చపాతీ పప్పు"},
     "category": "dinner", "region": "pan-india", "age_min": 18, "age_max": 72,
     "prep_time": 10, "cook_time": 20, "difficulty": "easy",
     "description": "Classic soft chapati with mild dal.",
     "ingredients": ["1/2 cup wheat flour", "2 tbsp moong dal", "1 tsp ghee", "Pinch turmeric"],
     "steps": ["Knead soft dough, rest 10 min", "Cook dal with turmeric", "Roll and cook thin chapatis", "Serve with dal"],
     "nutrition": {"calories": 240, "protein": 9, "carbs": 40, "fat": 5},
     "image": "https://images.pexels.com/photos/9609837/pexels-photo-9609837.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Mild Chicken Curry Rice", "hi": "चिकन करी", "te": "చికెన్ కూర"},
     "category": "dinner", "region": "pan-india", "age_min": 24, "age_max": 72,
     "prep_time": 15, "cook_time": 25, "difficulty": "medium",
     "description": "Mildly spiced chicken — protein source.",
     "ingredients": ["50g chicken minced", "1 tomato pureed", "1/2 cup rice", "Mild spices"],
     "steps": ["Cook chicken with tomato puree", "Simmer until tender", "Serve with rice"],
     "nutrition": {"calories": 280, "protein": 16, "carbs": 32, "fat": 8, "protein_level": "high"},
     "image": "https://images.pexels.com/photos/5560802/pexels-photo-5560802.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.5},
    {"title": {"en": "Dal Tadka", "hi": "दाल तड़का", "te": "పప్పు తాలింపు"},
     "category": "dinner", "region": "pan-india", "age_min": 18, "age_max": 72,
     "prep_time": 5, "cook_time": 15, "difficulty": "easy",
     "description": "Yellow lentils with gentle tempering.",
     "ingredients": ["1/4 cup toor dal", "Pinch turmeric", "1 tsp ghee", "Pinch cumin"],
     "steps": ["Pressure cook dal with turmeric", "Temper with ghee and cumin", "Serve with rice or roti"],
     "nutrition": {"calories": 160, "protein": 9, "carbs": 22, "fat": 4},
     "image": "https://images.pexels.com/photos/5560742/pexels-photo-5560742.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Paneer Bhurji", "hi": "पनीर भुर्जी", "te": "పనీర్ భుర్జీ"},
     "category": "dinner", "region": "north", "age_min": 24, "age_max": 72,
     "prep_time": 5, "cook_time": 10, "difficulty": "easy",
     "description": "Scrambled paneer with veggies.",
     "ingredients": ["50g paneer crumbled", "1 small tomato", "Pinch turmeric", "1 tsp ghee"],
     "steps": ["Sauté tomato in ghee", "Add paneer and turmeric", "Scramble 5 min", "Serve with roti"],
     "nutrition": {"calories": 220, "protein": 12, "carbs": 6, "fat": 16, "calcium": "high"},
     "image": "https://images.pexels.com/photos/5560771/pexels-photo-5560771.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "Idli Sambar", "hi": "इडली सांभर", "te": "ఇడ్లీ సాంబార్"},
     "category": "dinner", "region": "south", "age_min": 24, "age_max": 72,
     "prep_time": 10, "cook_time": 25, "difficulty": "medium",
     "description": "Steamed rice cakes with lentil stew.",
     "ingredients": ["Mini idlis", "Mild sambar"],
     "steps": ["Steam mini idlis", "Prepare mild sambar", "Serve together"],
     "nutrition": {"calories": 220, "protein": 8, "carbs": 38, "fat": 4},
     "image": "https://images.pexels.com/photos/14737070/pexels-photo-14737070.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Dosa with Potato", "hi": "डोसा आलू", "te": "దోస ఆలూ"},
     "category": "dinner", "region": "south", "age_min": 30, "age_max": 72,
     "prep_time": 10, "cook_time": 10, "difficulty": "medium",
     "description": "Crispy dosa with mild potato filling.",
     "ingredients": ["Dosa batter", "1 boiled potato mashed", "Pinch turmeric", "1 tsp ghee"],
     "steps": ["Spread thin dosa on tawa", "Mix potato with spices", "Fill and fold dosa", "Serve"],
     "nutrition": {"calories": 230, "protein": 6, "carbs": 40, "fat": 6},
     "image": "https://images.pexels.com/photos/9609843/pexels-photo-9609843.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.8},
    {"title": {"en": "Fish Curry Rice", "hi": "मछली चावल", "te": "చేప కూర అన్నం"},
     "category": "dinner", "region": "east", "age_min": 36, "age_max": 72,
     "prep_time": 10, "cook_time": 20, "difficulty": "medium",
     "description": "Mild fish curry with rice — omega-3 rich.",
     "ingredients": ["50g boneless fish", "1/2 cup rice", "1 tomato", "Mild spices"],
     "steps": ["Cook fish in mild tomato gravy", "Simmer 10 min", "Serve with rice"],
     "nutrition": {"calories": 260, "protein": 14, "carbs": 34, "fat": 6, "omega3": "high"},
     "image": "https://images.pexels.com/photos/5560758/pexels-photo-5560758.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.6},
    {"title": {"en": "Vegetable Khichdi", "hi": "सब्ज़ी खिचड़ी", "te": "కూరగాయల ఖిచడి"},
     "category": "dinner", "region": "pan-india", "age_min": 18, "age_max": 72,
     "prep_time": 10, "cook_time": 20, "difficulty": "easy",
     "description": "One-pot meal with rice, dal and vegetables.",
     "ingredients": ["1/4 cup rice", "2 tbsp moong dal", "Mixed veggies", "1 tsp ghee"],
     "steps": ["Pressure cook rice, dal, veggies together", "Mash lightly", "Top with ghee, serve warm"],
     "nutrition": {"calories": 240, "protein": 10, "carbs": 40, "fat": 5, "protein_level": "high"},
     "image": "https://images.pexels.com/photos/6646059/pexels-photo-6646059.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.9},
    {"title": {"en": "Tomato Soup with Bread", "hi": "टमाटर सूप", "te": "టొమాటో సూప్"},
     "category": "dinner", "region": "pan-india", "age_min": 18, "age_max": 72,
     "prep_time": 5, "cook_time": 15, "difficulty": "easy",
     "description": "Creamy tomato soup with soft bread.",
     "ingredients": ["2 tomatoes", "1 tsp ghee", "Pinch pepper", "1 slice bread"],
     "steps": ["Boil and puree tomatoes", "Heat with ghee and pepper", "Serve with toasted bread"],
     "nutrition": {"calories": 160, "protein": 4, "carbs": 24, "fat": 5, "vitamin_c": "high"},
     "image": "https://images.pexels.com/photos/5946636/pexels-photo-5946636.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.7},
    {"title": {"en": "Chana Masala Rice", "hi": "छोले चावल", "te": "శనగల కూర"},
     "category": "dinner", "region": "north", "age_min": 36, "age_max": 72,
     "prep_time": 480, "cook_time": 25, "difficulty": "medium",
     "description": "Chickpea curry with rice — protein rich.",
     "ingredients": ["1/4 cup soaked chana", "1/2 cup rice", "1 tomato", "Mild spices"],
     "steps": ["Pressure cook chana", "Make mild gravy", "Add chana, simmer", "Serve with rice"],
     "nutrition": {"calories": 280, "protein": 12, "carbs": 46, "fat": 5},
     "image": "https://images.pexels.com/photos/5560779/pexels-photo-5560779.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.6},
    {"title": {"en": "Oats Khichdi", "hi": "ओट्स खिचड़ी", "te": "ఓట్స్ ఖిచడి"},
     "category": "dinner", "region": "pan-india", "age_min": 18, "age_max": 72,
     "prep_time": 5, "cook_time": 12, "difficulty": "easy",
     "description": "Fiber-rich oats khichdi — soft and easy to digest.",
     "ingredients": ["1/4 cup oats", "2 tbsp moong dal", "Mixed veggies", "Pinch turmeric", "1 tsp ghee"],
     "steps": ["Pressure cook dal and oats", "Sauté veggies in ghee", "Mix all, simmer 3 min", "Serve warm"],
     "nutrition": {"calories": 210, "protein": 10, "carbs": 32, "fat": 5, "fiber": "high"},
     "image": "https://images.pexels.com/photos/6363500/pexels-photo-6363500.jpeg",
     "ayurvedic": False, "scientific": True, "rating": 4.7},
    {"title": {"en": "Stuffed Moong Roti", "hi": "मूंग रोटी", "te": "పెసర రొట్టె"},
     "category": "dinner", "region": "north", "age_min": 30, "age_max": 72,
     "prep_time": 15, "cook_time": 10, "difficulty": "medium",
     "description": "Moong dal stuffed wheat flatbread.",
     "ingredients": ["1/2 cup wheat flour", "2 tbsp cooked moong dal", "Pinch cumin", "1 tsp ghee"],
     "steps": ["Knead soft dough", "Stuff with spiced moong", "Roll and cook on tawa with ghee"],
     "nutrition": {"calories": 220, "protein": 9, "carbs": 34, "fat": 5},
     "image": "https://images.pexels.com/photos/5560764/pexels-photo-5560764.jpeg",
     "ayurvedic": True, "scientific": True, "rating": 4.6},
]
